theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Manual for the BSB-LAN Hard- & Software
url: "https://1coderookie.github.io"
baseurl: "/BSB-LPB-LAN_EN"
author: Ulf Dieckmann
lang: en-US
