theme: jekyll-theme-cayman #hacker
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: Manual for the BSB-LPB-LAN adapter
description: English language version of the manual for the BSB-LPB-LAN adapter and the BSB-LAN software.
url: https://1coderookie.github.io/BSB-LPB-LAN_EN
author: Ulf Dieckmann
lang: en-EN
